stages:
  - test
  - deploy

tests:
  stage: test
  script:
    - cd $DEPLOY_DIR
    - bash ./scripts/test.sh
  only:
    - master

deploy:
  stage: deploy
  script:
    - cd $DEPLOY_DIR
    - bash ./scripts/deploy.sh
  when: manual